# Generated by Django 2.0.6 on 2019-05-29 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BagJewel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bj_title', models.CharField(max_length=200)),
                ('bj_picture', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('bj_size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_title', models.CharField(max_length=200)),
                ('dress_picture', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('dress_size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pant_title', models.CharField(max_length=200)),
                ('pant_picture', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('pant_size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_title', models.CharField(max_length=200)),
                ('s_picture', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('s_size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShoesMen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_title', models.CharField(max_length=200)),
                ('sm_picture', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('sm_size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShoesWomen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sw_title', models.CharField(max_length=200)),
                ('sw_picture', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('sw_size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_title', models.CharField(max_length=200)),
                ('ts_picture', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('ts_size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('userForeignKey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tshirt',
            name='ts_ForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivoryApp.UserLoginModel'),
        ),
        migrations.AddField(
            model_name='shoeswomen',
            name='sw_ForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivoryApp.UserLoginModel'),
        ),
        migrations.AddField(
            model_name='shoesmen',
            name='sm_ForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivoryApp.UserLoginModel'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='s_ForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivoryApp.UserLoginModel'),
        ),
        migrations.AddField(
            model_name='pants',
            name='pant_ForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivoryApp.UserLoginModel'),
        ),
        migrations.AddField(
            model_name='dress',
            name='dress_ForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivoryApp.UserLoginModel'),
        ),
        migrations.AddField(
            model_name='bagjewel',
            name='bj_ForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivoryApp.UserLoginModel'),
        ),
    ]
