# Generated by Django 2.0.6 on 2019-05-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagjewel',
            name='bj_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dress',
            name='dress_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pants',
            name='pant_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shirt',
            name='s_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoesmen',
            name='sm_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoeswomen',
            name='sw_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='ts_price',
            field=models.IntegerField(default=0),
        ),
    ]
