# Generated by Django 2.0.6 on 2019-06-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivoryApp', '0002_auto_20190531_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloginmodel',
            name='profilePic',
        ),
    ]
