# Generated by Django 2.0.6 on 2019-06-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivoryApp', '0003_remove_userloginmodel_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirt',
            name='ts_size',
        ),
    ]
