# Generated by Django 2.0.6 on 2019-06-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivoryApp', '0004_remove_tshirt_ts_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagjewel',
            name='bj_size',
        ),
        migrations.RemoveField(
            model_name='dress',
            name='dress_size',
        ),
        migrations.RemoveField(
            model_name='pants',
            name='pant_size',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='s_size',
        ),
        migrations.RemoveField(
            model_name='shoesmen',
            name='sm_size',
        ),
        migrations.RemoveField(
            model_name='shoeswomen',
            name='sw_size',
        ),
    ]
