# Generated by Django 2.0.6 on 2019-06-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivoryApp', '0005_auto_20190604_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='ts_size',
            field=models.CharField(default='small', max_length=20),
            preserve_default=False,
        ),
    ]
